etv/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.core.urlresolvers import reverse
from django.contrib import admin
from etv import settings
from dajaxice import urls
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
from tastypie.api import Api
from users.api.api import UserProfileResource, UserResource

#Api RESTful
user_api_v1 = Api(api_name='user')
user_api_v1.register(UserResource())
user_api_v1.register(UserProfileResource())

admin.autodiscover()
dajaxice_autodiscover()

urlpatterns = patterns('',
       url(r'^elevate/', include(admin.site.urls)),
       (r'^grappelli/', include('grappelli.urls')),
       url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
       url(r'^register/$', 'users.views.registerFranchisee'),
       url(r'^register/login/$', 'django.contrib.auth.views.login', {'template_name': 'users/register_franchisee.html'}),
       url(r'^register/confirm/(?P<activation_key>\w+)', 'users.views.confirmFranchisee'),
       (r'^api/', include(user_api_v1.urls)),
       
)
if settings.DEBUG:
    # Serve static files
    urlpatterns += staticfiles_urlpatterns()
    # Serve uploaded files
    urlpatterns += patterns('',
        url(r'^uploads/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),
        )

users/models.py
# -*- coding: utf-8 -*-
from django.db import models, connection
from django.db.models.sql import InsertQuery
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _
from datetime import date, datetime
from django.db.models.signals import post_save
from users.classes.UsersCodes import UserCode
from users.classes.BulkInsert import Bulk
from django.conf import settings

from datetime import datetime

class UserProfile(models.Model):
    """
        It extends the model model user base that comes with django and gives
        the performance needed for working with user data
    """
    CITY = (
        (u'Bogotá',u'Bogotá'),
        (u'Cali',u'Cali'),
        (u'Barranquilla',u'Barranquilla'),
        (u'Medellin',u'Medellin'),        
    )
    identification = models.OneToOneField(User, primary_key=True)
    refFranchisee  = models.ForeignKey('self', help_text="Usuario Franqiciado que lo referencia", verbose_name="Franquiciado Referenciado", blank=True, null=True)
    city           = models.CharField(max_length=60, choices= CITY, help_text="Ciudad donde vive", verbose_name="Ciudad", blank=True, null=True)
    dateOfBirth    = models.DateField(help_text="Fecha de Nacimiento", verbose_name="Indique la Fecha de Nacimiento", blank=True, null=True)
    photo          = models.ImageField(help_text="Foto del Usuario", verbose_name="Foto", blank=True, null=True, upload_to="uploads")
    phone          = models.CharField(max_length=60, help_text="Número de Telefono de contacto", verbose_name="Telefono", blank=True, null=True)
    mobile         = models.CharField(max_length=60, help_text="Número de Telefono móvil de contacto", verbose_name="Telefono móvil", blank=True, null=True)
    alternativePhone = models.CharField(max_length=60, help_text="Número de Telefono o FAX", verbose_name="Telefono/FAX", blank=True, null=True)
    address        = models.CharField(max_length=60, help_text="Dirección de Residencia", verbose_name="Dirección", blank=True, null=True)
    lastAccess     = models.DateTimeField(auto_now=True, editable=False)
    #user activation through product registration
    activationKey  = models.CharField(max_length=60, editable=False, blank=True, null=True)
    keyExpires     = models.DateTimeField(editable=False, blank=True, null=True)
    refFranchiseeCode = models.CharField(max_length=20, editable=False, blank=True, null=True, unique=True)
    
    class Meta:
        ordering = ['identification']
    
    def __unicode__(self):
            return "%s" %(self.identification) 

def createUser(sender, instance, created, **kwargs):
        if created:
           profile = UserProfile()
           profile.identification = instance
           profile.save
            
post_save.connect(createUser, sender=User)

class CreateCodes(models.Model):
    """
        This model is based on the class 'BulkInsert' to create the 20 codes that are
        assigned to the franchisee or franchisee referenced and anchor with
        your franchisee level
    
    """
    franchisee  = models.ForeignKey('UserProfile', to_field='identification')
    code        = models.CharField(max_length=20, editable=False, unique=True)
    useFlagCode = models.BooleanField(default=False, editable=False)
    dateUseFlag = models.DateTimeField(editable=False, blank=True, null=True)
    dateCreateCode = models.DateTimeField(auto_now_add=True, editable=False)
    
    def __unicode__(self):
        return "%s %s"%(self.franchisee, self.code)
    
    # saving codes generated for franchisees 
    def save(self):
        """
            is sent to the class UserCode parameter of 20 and 8 for the number
            of codes and code length.
        """
        bulk = Bulk(); values = []; self.cod = UserCode(20,8)
        self.codes = self.cod.generateCodes()
        for i in range(len(self.codes)):values.append(CreateCodes(franchisee = self.franchisee, code = self.codes[i], useFlagCode = False, dateUseFlag = None, dateCreateCode = datetime.now()))
        bulk.insertMany(CreateCodes,values)

users/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms import widgets
from django.contrib.auth.models import User
from users.models import CreateCodes, UserProfile

class RegistrationFormFranchisee(forms.Form):
    # Fields for the creation of the user who is not registered
    identification = forms.CharField(min_length=8, max_length=12, widget=forms.TextInput(attrs={'placeholder':'Usuario en el Sistema', 'class':'span3'}))
    email          = forms.EmailField(min_length=6, max_length=40, widget=forms.TextInput(attrs={'placeholder':'email', 'class':'span3'}))
    passwordOne    = forms.CharField(min_length=6, max_length=20, widget=forms.PasswordInput(render_value=False, attrs={'placeholder':'Escriba la Contraseña', 'class':'span3'}))
    passwordTwo    = forms.CharField(min_length=6, max_length=20, widget=forms.PasswordInput(render_value=False, attrs={'placeholder':'Repita la Contraseña', 'class':'span3'}))
    franchiseeCode = forms.CharField(max_length=8, widget=forms.TextInput(attrs={'placeholder':'Código Franquiciado', 'class':'span3'}), required=False, initial=None)
    
    # Method for verifying that the user and data is not in the database
    def isValidFranchisee(self, franchisee):
        try:
            User.objects.get(username=franchisee)
        except User.DoesNotExist:
            return True
        return False
    
    def isValidFranchiseeEmail(self, email):
        try:
            User.objects.get(email=email)
        except User.DoesNotExist:
            return True
        return False
    
    def isValidFranchiseeCode(self, franchiseeCode):
        try:
            franchiseeReg = CreateCodes.objects.get(code=franchiseeCode) 
        except CreateCodes.DoesNotExist:
            # checking if the field is blank franchiseeCode or invalid 
            if franchiseeCode == '':
                return {'message':u'No suministra código de referencia para Franquiciado', 'flag':True, 'id':0}
            #invalid FranchiseeCode
            return {'message':u'Este código No existe', 'flag':None, 'id':None}
        # if users code is used or not
        if franchiseeReg.useFlagCode == True:
            return {'message':u'Este código ya esta en Uso', 'flag':False, 'id':-1}
        else:
            return {'message': u'La cedula del franquiciado que te referencia es %s' % (str(franchiseeReg.franchisee.identification.username)), 'flag': True, 'id': franchiseeReg.franchisee.identification.id}
    
    # Method for creating the user in the database
    def save(self, data):
        newUser = User.objects.create_user(data['identification'],
                                    data['email'],
                                    data['passwordOne'])
        newUser.is_active = False
        newUser.save()
        return newUser
    
class LoginForm(forms.Form):
    identification = forms.CharField(min_length=8, max_length=12, widget=forms.TextInput(attrs={'placeholder':'Identificación', 'class':'span3'}))
    password       = forms.CharField(min_length=6, max_length=20, widget=forms.PasswordInput(render_value=False, attrs={'placeholder':'Contraseña', 'class':'span3'}))
    

users/views.py
import datetime, random, sha
from django import forms
from django.template import Context
from django.shortcuts import render_to_response, get_object_or_404
from users.models import UserProfile
from users.forms import RegistrationFormFranchisee, LoginForm
from django.template import RequestContext

def registerFranchisee(request):
    # enabled when not in production or not in the system
    
    if request.user.is_authenticated():
        # They already have an account; don't let them register again
        return render_to_response('users/register_franchisee.html', {'has_account':True})
    
    form = RegistrationFormFranchisee()

    context = {'title':'register','legend':u'Registrate como Franquiciado!','form_register':form, 'has_account':False}
    # Return context with clean Form register, This solves the problem of csrf_token
    return render_to_response('users/register_franchisee.html', context, context_instance=RequestContext(request))
    
"""

"""
def confirmFranchisee(request, activation_key):

    if request.user.is_authenticated():
        return render_to_response('users/confirm.html', {'has_account': True})
    
    user_profile = get_object_or_404(UserProfile, activationKey=activation_key)
    print user_profile.keyExpires
    print datetime.datetime.today()
    
    if user_profile.keyExpires < datetime.datetime.today():
        return render_to_response('users/confirm.html', {'expired': True})
    
    user_account = user_profile.identification
    print user_account
    user_account.is_active = True
    user_account.save()
    return render_to_response('users/confirm.html', {'success': True})
"""
def loginUser(request):
    if request.user.is_authenticated():
        return render_to_response('users/confirm.html', {'has_account': True})
    login_form = LoginForm()
    print login_form
    context = {'login_form':login_form, 'has_account':False, 'register':'hola mundo'}
    return render_to_response('users/register_franchisee.html', context, context_instance=RequestContext(request))
"""

etv/templates/users/base.html
<!DOCTYPE html>
{% load dajaxice_templatetags %}
    <html lang='es'>
        <head>
            <meta charset='utf-8' />
            <!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
            <!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
            <!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
            <!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
            <title>{{ title }}</title>
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <script src="/static/grappelli/jquery/jquery-1.7.2.min.js" type="text/javascript"></script>
            <link rel="stylesheet" type="text/css" href="/static/assets/css/bootstrap.min.css" />
            <script src="/static/assets/js/jquery.validate.min.js" type="text/javascript"></script>
            {% dajaxice_js_import %}
            <script src="/static/dajax/jquery.dajax.core.js" type="text/javascript"></script>
            <script src="/static/assets/js/bootstrap.min.js" type="text/javascript"></script>
            <script src="/static/assets/js/animation.js" type="text/javascript"></script>
	    </script>
            	{% block extrajs %}
                {% endblock %}
        </head>
        <body>
            <div class="container-fluid">
                <div class="navbar navbar-inverse">
                    <div class="navbar-inner">
                      <a class="brand" href="#">ElevaTusVentas.co</a>
                      <ul class="nav">
                        <li class="active"><a href="#">Home</a></li>
                        <li><a href="#">Franquiciados</a></li>
                        <li><a href="#">Clientes</a></li>
                        <li><a href="#">Contactenos</a></li>
                        </ul>
                      <ul class="nav pull-right">
                        <li><a role="button" href="#loginModal" data-toggle="modal"><i class="icon-user icon-white"></i> Ingreso al Sistema</a>
                      </ul>
                    </div>
                  </div>
                {% block content %}
            {% endblock %}
        </body>
    </html>

etv/templates/users/confirm.html
{% extends "users/base.html" %}
{% load dajaxice_templatetags %}
	{% block content %}
            {% if has_account %}
                <div class="alert alert-block">
		    <p>
		    <h3>¡Alerta!</h3>
		    <h4><strong>¡Ya estas registrado y eres un Franquiciado activo en el sistema!</strong></h4>
		    </p><br />
		    <p>
			<button class="btn btn-danger" type="button">Regregar al Menú General</button>
		    </p>
		</div>
            {% else %}
            <div class="alert alert-success">
                <h3>¡Felicitaciones!</h3>
                <h4><strong>Ya eres un Franquiciado en elevatusventas.com</strong></h4><br />
                <button class="btn btn-large btn-primary" type="button">Ingresa al Sistema!</button>
            </div>
            {% endif %}
        {% endblock %}

etv/templates/users/register.html
{% extends "users/base.html" %}
{% load dajaxice_templatetags %}    
            	{% block extrajs %}
	    {% endblock %}
	    {% block content %}
            <div class="container-fluid">
                <div class="span6">
                <form method='post' id="my_form" action='/thanks/'>{% csrf_token %}
                <fieldset>
                    <legend class="lead">{{ legend }}</legend>
                    {{ form.non_field_errors }}
		    <div id='errors' class="alert alert-info">
			<b>Saludos!</b> Por favor diligenciar los campos marcados con <b>*</b> son necesarios
		    </div>
			<div class="controls">
			    <div id="f_identification">
			    {{ form.identification.errors }}
			    <label class="control-label" for="id_identification">Cedula o Identificación</label>
				{{form.identification}}
			    </div>
			</div>
			<div class="controls">
			    <div id="f_email">
			    {{ form.email.errors }}
			    <label class="control-label" for="id_email">Correo electronico</label>
				{{form.email}}
			    </div>
			</div>
			<div class="controls">
			    <div id="f_passwordOne">
			    {{ form.passwordOne.errors }}
			    <label class="control-label" for="id_passwordOne">Contraseña</label>
				{{form.passwordOne}}
			    </div>
			</div>
			<div class="controls">
			    <div id="f_passwordTwo">
			    {{ form.passwordTwo.errors }}
			    <label class="control-label" for="id_passwordTwo">Verificación Contraseña</label>
				{{form.passwordTwo}}
			    </div>
			</div>
			<div class="controls">
			    <div id="f_franchiseeCode">
			    {{ form.franchiseeCode.errors }}
			    <label class="control-label" for="id_franchiseeCode">Código de Referencia</label>
				{{form.franchiseeCode}}
			    </div>
			</div>
			<input data-toggle="modal" class="btn btn-primary" role="button" id="buttonSend" value="Registarme!" />
                </fieldset>
                </form>
                </div>
            </div>
	    
	    <!-- Modal Register-->
	    <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	      <div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3 id="myModalLabel">Bienvenido! Gracias por Registrarte</h3>
	      </div>
	      <div class="modal-body">
		<p></p>
	      </div>
	      <div class="modal-footer">
		<button class="btn btn-primary" data-dismiss="modal" aria-hidden="true">Close</button>
	      </div>
	    </div>
	    {% endblock %}

etv/templates/users/register_franchisee.html
{% extends "users/base.html" %}
{% load dajaxice_templatetags %}
	{% block content %}
	    {% if has_account %}
		<div class="alert alert-block">
		    <p>
		    <h3>¡Alerta!</h3>
		    <h4>¡Ya estas registrado y eres un Franquiciado activo en el sistema!</h4>
		    </p><br />
		    <p>
			<button class="btn btn-danger" type="button">Regregar al Menú General</button>
		    </p>
		</div>
	    {% else %}
                <div class="span6">
                <form method='post' id="my_form" accept-charset="utf-8">{% csrf_token %}
                <fieldset>
                    <legend class="lead">{{ legend }}</legend>
                    {{ form_register.non_field_errors }}
		    <div id='errors' class="alert alert-info">
			<b>Saludos!</b> Por favor diligenciar los campos marcados con <b>*</b> son necesarios
		    </div>
			<div class="controls">
			    <div id="f_identification">
			    {{ form_register.identification.errors }}
			    <label class="control-label" for="id_identification">Cedula o Identificación</label>
				{{form_register.identification}}
			    </div>
			</div>
			<div class="controls">
			    <div id="f_email">
			    {{ form_register.email.errors }}
			    <label class="control-label" for="id_email">Correo electronico</label>
				{{form_register.email}}
			    </div>
			</div>
			<div class="controls">
			    <div id="f_passwordOne">
			    {{ form_register.passwordOne.errors }}
			    <label class="control-label" for="id_passwordOne">Contraseña</label>
				{{form_register.passwordOne}}
			    </div>
			</div>
			<div class="controls">
			    <div id="f_passwordTwo">
			    {{ form_register.passwordTwo.errors }}
			    <label class="control-label" for="id_passwordTwo">Verificación Contraseña</label>
				{{form_register.passwordTwo}}
			    </div>
			</div>
			<div class="controls">
			    <div id="f_franchiseeCode">
			    {{ form_register.franchiseeCode.errors }}
			    <label class="control-label" for="id_franchiseeCode">Código de Referencia</label>
				{{form_register.franchiseeCode}}
			    </div>
			</div>
			<input data-toggle="modal" class="btn btn-primary" role="button" id="buttonSend" value="Registarme!" />
                </fieldset>
                </form>
            </div>
	    
	    <!-- Modal Register-->
	    <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	      <div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
		<h3 id="myModalLabel">Lee la siguiente información</h3>
	      </div>
	      <div class="modal-body" id="modalBody">
	      </div>
	      <div class="modal-footer">
		<button class="btn btn-primary" data-dismiss="modal" aria-hidden="true">Cerrar</button>
	      </div>
	    </div>
	    {% if form.errors %}
		{% endif %}
	    <div id="loginModal" class="modal hide fade">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                          <h3>Ingreso al Sistema {{ register }}</h3>
                        </div>
                        <div class="modal-body">
                          <form id="login" class="form-horizontal" method="post" action="{% url django.contrib.auth.views.login %}">{% csrf_token %}
            
                                <div class="control-group">
                                  <label class="control-label" for="id_identification">Identificación</label>
                                  <div class="controls">
                                    {{form.username}}
                                  </div>
                                </div>
                                <div class="control-group">
                                  <label class="control-label" for="id_password">Contraseña</label>
                                  <div class="controls">
                                    {{form.password}}
                                  </div>
                                </div>
                                <div class="control-group">
                                  <div class="controls">
                                    <label class="checkbox">
                                      <input type="checkbox"> Recordar cuenta
                                    </label>
                                    <button id="buttonLogin" type="submit" class="btn btn-primary">Ingresar</button>
				    <input type="hidden" name="next" value="{{ next }}" />
                                  </div>
                                </div>
                              </form>
                        </div>
                        <div class="modal-footer">
                        </div>
                      </div>
                    </div>
	    {% endif %}
	{% endblock %}